# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accessibility_type',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Blind', 'Blind / Low Vision'), ('Deaf', 'Deaf / Hard of Hearing'), ('Speech', 'Speech Impaired'), ('Motor', 'Motor Disability')], default='None', max_length=20),
        ),
        migrations.CreateModel(
            name='DoctorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
